collections:
  my_collection:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "my-site"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      author: "A Jaspan"
name: My Blog!
description: A blog about Data Science
favicon: favicon.ico
theme: jekyll-theme-architect
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
#   extensions: fenced_code_blocks
